name: EngravingEnchant
version: 1.0.0
main: me.lgdtimtou.engravingenchant.Main
api-version: 1.16

commands: 
   engrave:
      description: "<itemtype/add/list> (<player_name>)"
      aliases: en
      permissions: 
         engrave.command.add:
         engrave.command.list:
         engrave.command.itemtype:
         
   